### ISSUE TITLE
Can't add handle to Discord connections

### ISSUE THREAD

**Issue by qxtal** [furSUDO/simple-atproto-handles#3]
When trying to add a handle as a connection on Discord, it returns an error stating "HANDLE - An unknown error occurred. Maybe check your handle?". I've tried with and without the `@` prefix, but no dice. At least 2 other members of my instance have reported the same issue of not being able to add the handle to their Discord connections

**Comment by furSUDO** [comment]
Hey @qxtal, unfortunately, this may not be fixed as the core limitation is from Cloudflare.

Since Cloudflare pages do not support subdomains, we rewrite incoming requests using redirects from `https://*.example.com/*` to `https://example.com/$1/$2`, to effectively catch the subdomain and still return the `did:` of the associated Bluesky account.

While Discord is returning this error, Simple-ATProto-Handles's method is fully within Bluesky's ATProtocol's Spec. As such, this would most likely be an edge case that Discord would have to consider when checking handles.
